services:
  product-service:
    build: .
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
      - /app/.venv
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://root:toor@product-db:5432/products
    depends_on:
      - product-db

  product-db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=products
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - product-db-data:/var/lib/postgresql

volumes:
  product-db-data:
    driver: local
