services:
  product-service:
    build: .
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./:/app
      - /app/.venv
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://root:toor@product-db:5432/products
      - AUTH_GRPC_CLIENT_HOST=localhost
      - AUTH_GRPC_CLIENT_PORT=50051
      - RABBITMQ_URL=amqp://guest:guest@localhost:5672/
    depends_on:
      - product-db
    networks:
      - product-service-network

  product-db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=products
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - product-db-data:/var/lib/postgresql
    networks:
      - product-service-network

volumes:
  product-db-data:
    driver: local

networks:
  product-service-network:
    driver: bridge
